### ISSUE TITLE
シミュレーションが起動できない

### ISSUE THREAD

**Issue by TK-19** [agent-system/lecture2019#11]
度々失礼いたします。aizuspider,jaxonを起動しようとすると以下のようなエラーが生じます。何卒宜しくお願い致します。

【aizuspider】
$ ./run_no_gl.sh roslaunch aizuspider_description aizuspider.launch
localuser:root being added to access control list
choreonoidsim
[aizuspider.launch] is neither a launch file in package [aizuspider_description] nor is [aizuspider_description] a launch file name
The traceback for the exception was written to the log file

【jaxon】
$ ./run_no_gl.sh rtmlaunch hrpsys_choreonoid_tutorials create_environment_sample.launch ROBOT_SETTING_YAML:=/choreonoid_ws/src/aizuspider_description/jaxon_task1.yaml
localuser:root being added to access control list
choreonoidsim

Mon Jun 10 05:43:34 2019:

Starting omniNames for the first time.
Wrote initial log file.
Read log file successfully.
Root context is IOR:010000002b00000049444c3a6f6d672e6f72672f436f734e616d696e672f4e616d696e67436f6e746578744578743a312e300000010000000000000070000000010102000e00000031302e3231332e33392e313030009d3a0b0000004e616d6553657276696365000300000000000000080000000100000000545441010000001c00000001000000010001000100000001000105090101000100000009010100035454410800000006eefd5c01000021
Checkpointing Phase 1: Prepare.
Checkpointing Phase 2: Commit.
Checkpointing completed.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 589, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: jsk_footstep_controller
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/catkin_ws/src/jsk_common/jsk_coordination_system/dynamic_tf_publisher
ROS path [2]=/catkin_ws/src/rtmros_choreonoid/hrpsys_choreonoid
ROS path [3]=/catkin_ws/src/rtmros_common/hrpsys_tools
ROS path [4]=/catkin_ws/src/jsk_common/jsk_topic_tools
ROS path [5]=/catkin_ws/src/jsk_robot/jsk_robot_common/jsk_robot_startup
ROS path [6]=/catkin_ws/src/rtmros_choreonoid/jvrc_models
ROS path [7]=/catkin_ws/src/rtmros_common/openrtm_tools
ROS path [8]=/catkin_ws/src/pr2_navigation/pr2_navigation_self_filter
ROS path [9]=/catkin_ws/src/rtmros_common/rtmbuild
ROS path [10]=/catkin_ws/src/rtmros_common/hrpsys_ros_bridge
ROS path [11]=/catkin_ws/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials
ROS path [12]=/catkin_ws/src/rtmros_choreonoid/hrpsys_choreonoid_tutorials
ROS path [13]=/hrpsys_ws/src/openhrp3
ROS path [14]=/hrpsys_ws/src/hrpsys
ROS path [15]=/hrpsys_ws/devel/
ROS path [16]=/opt/ros/kinetic/share
[rtmlaunch] default corbaport:= 15005 will be used
[rtmlaunch] Start omniNames at port 15005 
... logging to /root/.ros/log/b012e882-8b42-11e9-85d2-b46bfcdcdaca/roslaunch-tk-spec15-x360-1.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

**Comment by YoheiKakiuchi** [comment]
どこかが最新ではないように思われるので、

ソースを最新にすることと、
~~~
cd robotsimulation-docker/choreonoid_docker
git pull
~~~

dockerイメージを最新にすることを行ってみてください
~~~
docker pull choreonoidsim:16.04_release-1.7
もしくは
docker pull choreonoidsim:16.04_no_gl_release-1.7
~~~

**Comment by TK-19** [comment]
無事シミュレーションが起動しました。ありがとうございます！
